apiVersion: skaffold/v2beta6
kind: Config
build:
  artifacts:
  - image: vacuum
    docker:
      target: dev
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - charts/timescaledb-secrets.yaml
    flags:
      global:
        - --namespace=vacuum
  helm:
    releases:
      - chartPath: charts/vacuum
        namespace: vacuum
        name: vacuum
        artifactOverrides:
          image: vacuum
        setFiles:
          config: config.yaml
      - chartPath: charts/timescaledb-single
        namespace: vacuum
        name: timescaledb
        valuesFiles:
          - charts/timescaledb.yaml
      - chartPath: stable/grafana
        namespace: vacuum
        name: grafana
        remote: true
        valuesFiles:
          - charts/grafana.yaml
        # setFiles:
        #   dashboards.default.BTC_USDT.json: dashboards/BTC_USDT.json
portForward:
  - namespace: vacuum
    resourceType: service
    resourceName: vacuum
    port: 80
    localPort: 5000
  - namespace: vacuum
    resourceType: pod
    resourceName: timescaledb-0
    port: 5432
    localPort: 5432
  - namespace: vacuum
    resourceType: service
    resourceName: grafana
    port: 80
    localPort: 3000
