apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vacuum.fullname" . }}-config
  labels:
    {{- include "vacuum.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  config.yaml:
    {{- toYaml . | nindent 4 }}
  {{- end }}
