#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."


namespace=grub-bin-bot


echo "+++ Forwarding postgresql port"
kubectl port-forward --namespace "${namespace}" svc/postgresql 5432:5432
