#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."


namespace=grub-bin-bot


echo "+++ Forwarding ports to Minikube services"
kubectl port-forward --namespace "${namespace}" svc/postgresql 5432:5432 &
kubectl port-forward --namespace "${namespace}" svc/grafana 3000:3000 &

trap 'kill $(jobs -p)' EXIT
