#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."


namespace=grub-bin-bot


echo "+++ Forwarding grafana port"
pod_name=$(kubectl get pods --namespace "${namespace}" \
  -l "app.kubernetes.io/name=grafana,app.kubernetes.io/instance=grafana" \
  -o jsonpath="{.items[0].metadata.name}")

kubectl --namespace "${namespace}" port-forward "${pod_name}" 3000
