#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."


namespace=grub-bin-bot


echo "+++ Forwarding ports to Minikube services"

for pod in timescaledb grafana; do
  echo "Waiting for ${pod}..."
  while ! kubectl get pods --namespace grub-bin-bot | grep "${pod}" | grep "1/1" >/dev/null; do
    sleep 1
  done
done

trap 'kill $(jobs -p)' EXIT
kubectl port-forward --namespace "${namespace}" pod/timescaledb-0 5432:5432 &
kubectl port-forward --namespace "${namespace}" svc/grafana 3000:80 &

read -r -d '' _ </dev/tty
