#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."


namespace=grub-bin-bot


echo "+++ Add stable helm repo"
helm repo add stable https://kubernetes-charts.storage.googleapis.com

echo "+++ Add bitnami helm repo"
helm repo add bitnami https://charts.bitnami.com/bitnami

echo "+++ Install or upgrade postgresql helm chart"
helm upgrade \
  --install \
  --namespace "${namespace}" \
  --create-namespace \
  --values monitoring/postgresql-values.yaml \
  postgresql \
  bitnami/postgresql

echo "+++ Install or upgrade grafana helm chart"
helm upgrade \
  --install \
  --namespace "${namespace}" \
  --create-namespace \
  --values monitoring/grafana-values.yaml \
  grafana \
  stable/grafana
