#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."


namespace=grub-bin-bot


if ! kubectl get namespaces | grep "${namespace}" >/dev/null; then
  echo "+++ Create namespace ${namespace}"
  kubectl create namespace "${namespace}"
fi

if ! kubectl get secrets --namespace "${namespace}" | grep timescaledb >/dev/null; then
  echo "+++ Install TimescaleDB secrets"
  kubectl apply \
    --namespace "${namespace}" \
    --kustomize charts/timescaledb-secrets
fi

echo "+++ Install TimescaleDB Helm chart"
helm upgrade \
  --install \
  --namespace "${namespace}" \
  --values charts/timescaledb.yaml \
  timescaledb \
  charts/timescaledb-single

echo "+++ Install or upgrade Grafana Helm chart"
helm upgrade \
  --install \
  --namespace "${namespace}" \
  --values charts/grafana.yaml \
  --set-file dashboards.default.BTC_USDT.json=dashboards/BTC_USDT.json \
  grafana \
  stable/grafana
