#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."


namespace=grub-bin-bot


echo "+++ Add stable helm repo"
helm repo add stable https://kubernetes-charts.storage.googleapis.com

echo "+++ Add bitnami helm repo"
helm repo add bitnami https://charts.bitnami.com/bitnami

echo "+++ Install or upgrade postgresql helm chart"
helm upgrade \
  --install \
  --namespace "${namespace}" \
  --create-namespace \
  --values charts/postgresql.yaml \
  --set-file initdbScripts."seed\.sql"=sql/seed.sql \
  postgresql \
  bitnami/postgresql

echo "+++ Install or upgrade grafana helm chart"
helm upgrade \
  --install \
  --namespace "${namespace}" \
  --create-namespace \
  --values charts/grafana.yaml \
  --set-file dashboards.default.BTC_USDT.json=dashboards/BTC_USDT.json \
  grafana \
  stable/grafana
