---
name: tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          pwd
          ls -al
          cd grub-bin-bot
          poetry config virtualenvs.in-project true
          poetry install

      - name: black
        run: |
          cd grub-bin-bot
          poetry run black .

      - name: flake8
        run: |
          cd grub-bin-bot
          poetry run flake8

      - name: mypy
        run: |
          cd grub-bin-bot
          poetry run mypy .

  test:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          cd grub-bin-bot
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run tests
        run: |
          cd grub-bin-bot
          poetry run pytest
